version: 2
dependencies:
  pre:
    - sudo apt-get update; sudo apt-get install ruby-sass
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          sudo apt-get update; sudo apt-get install ruby-sass
      - run:
          git config --global user.email "baylessjonathan@gmail.com" > /dev/null 2>&1
          git config --global user.name "$baylessj-circleci" > /dev/null 2>&1
          git init
          remote=$(git config remote.origin.url)
          git remote add --fetch origin "$remote"
          git checkout master
      - run:
          sass css/main.scss\:css/main.css
      - run:
          git add -A
          git commit --allow-empty -m "CI Build [ci skip]"
          git push --force --quiet origin master
