version: 2
dependencies:
  pre:
    - sudo apt-get update; sudo apt-get install ruby-sass
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    pre:
      - sudo apt-get update; sudo apt-get install ruby-sass
    steps:
      - checkout
      - run:
          sass css/main.scss\:css/main.css
